DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS quizzers;
DROP TABLE IF EXISTS districts;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS scores;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  district TEXT NOT NULL,
  role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  district TEXT NOT NULL,
  coach TEXT
);

CREATE TABLE IF NOT EXISTS quizzers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  team_id INTEGER NOT NULL,
  FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE IF NOT EXISTS districts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quizzes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quiz_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    quizzer_id INTEGER NOT NULL,
    question_number INTEGER NOT NULL,
    score TEXT NOT NULL,
    FOREIGN KEY (quiz_id) REFERENCES quizzes (id),
    FOREIGN KEY (team_id) REFERENCES teams (id),
    FOREIGN KEY (quizzer_id) REFERENCES quizzers (id)
);
